# Generated by Django 4.0.3 on 2023-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('species', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='flowerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('point', models.CharField(max_length=70)),
                ('bloom', models.CharField(max_length=70)),
                ('toxin', models.CharField(max_length=70)),
            ],
        ),
    ]
