# Generated by Django 4.0.3 on 2023-01-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('s3_url', models.TextField()),
                ('poison', models.BooleanField(default=False)),
                ('symptom', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('flower_language', models.CharField(max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
    ]