# Generated by Django 4.0.3 on 2023-01-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flower',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
